from typing import Protocol
from src.models.contest import ContestInfo
from src.models.analysis import ContestAnalysis
from src.models.artifact import ReportArtifact


class BaseCollector(Protocol):
    async def discover(self) -> list[ContestInfo]: ...
    async def fetch_details(self, contest_id: str) -> ContestInfo: ...
    def health_check(self) -> bool: ...


class BaseAnalyzer(Protocol):
    async def analyze(self, contest: ContestInfo) -> ContestAnalysis: ...
    async def classify_compliance(self, contest: ContestInfo) -> str: ...
    async def calculate_roi(self, analysis: ContestAnalysis) -> float: ...


class BaseGenerator(Protocol):
    async def generate(
        self, contest: ContestInfo, analysis: ContestAnalysis
    ) -> ReportArtifact: ...
    async def improve(
        self, artifact: ReportArtifact, feedback: str
    ) -> ReportArtifact: ...


class BaseNotifier(Protocol):
    async def notify_deadline(
        self, contest: ContestInfo, days_remaining: int
    ) -> None: ...
    async def notify_review_ready(self, artifact: ReportArtifact) -> None: ...
